stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

deploy:
  stage: deploy
  script:
    - kubectl apply -f kubernetes/deployment.yaml -n $CI_COMMIT_REF_NAME
    - kubectl apply -f kubernetes/service.yaml -n $CI_COMMIT_REF_NAME
  only:
    - develop
    - production
